version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    # Uncomment the following lines if you need to mount volumes for development
    # volumes:
    #   - ./src:/app/src
    restart: unless-stopped
